export const bulb = `<img src="../resource/light-bulb-idea-svgrepo-com.svg" alt=""/>`
export const bright = `style="background-color: #FAAE7B"`;
export const crossingBulbs = `style="background-color: #FF7D7D"`;
export const obstacleWithCorrectAmountBulb = `style="background-color: #000000; color: #4E9F3D"`;
export const dark = `style="background-color: #623A73"`;
export const obstacle = `style="background-color: #000000"`;
export const menuDiv = document.querySelector("#menu");
export const playerNameInput = document.querySelector("#player-name-input");
export const loadEasyButton = document.querySelector("#easy");
export const loadNormalButton = document.querySelector("#normal");
export const loadHardButton = document.querySelector("#hard");
export const loadSavedGameButton = document.querySelector("#saved-game");
export const detailsButton = document.querySelector("#details-button");
export const recentGamesDiv = document.querySelector("#recent-games");
export const detailsDiv = document.querySelector("#details");
export const gameDiv = document.querySelector("#game");
export const tableElement = document.querySelector("#play-field");
export const playerNameParagraph = document.querySelector("#player-name");
export const timerParagraph = document.querySelector("#timer");
export const playAgainButton = document.querySelector("#play-again");